import "./globals.css";
import { Providers } from "./GlobalState/Provider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  favicon: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
